### ISSUE TITLE
License

### ISSUE THREAD

**Issue by peterhcharlton** [Cassey2016/PPG_Peak_Detection#1]
Thanks for making these PPG peak detection algorithms publicly available, they will be a helpful resource.

I wondered, could you provide a license for the code? This would make it clear how it can be reused. Many thanks

**Comment by Cassey2016** [comment]
@peterhcharlton Hi Peter, thanks for your interest in our project and code. I just created an MIT License in the master branch 554c0ece780c29f4f41b110443cffde2b5973af7. Does that work for the reusability of our code? Thank you!

**Comment by peterhcharlton** [comment]
@Cassey2016  Excellent - yes thank you that makes it very clear. Thanks again
